//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Commands Generator.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using JCMG.EntitasRedux.Commands;
using Ecs.Commands.Commands;
using UnityEngine;
using Game.Utils.Units;
using System;

namespace Ecs.Commands
{
    public static partial class CommandBufferExtensions
    {
        public static void ReceiveDamage(this ICommandBuffer commandBuffer, GameEntity target, float damage)
        {
            ref var command = ref commandBuffer.Create<ReceiveDamageCommand>();
            command.Target = target;
            command.Damage = damage;
        }
        
        public static void SpawnUnit(this ICommandBuffer commandBuffer, Vector3 position, Quaternion rotation, EUnitType unitType, Boolean isPlayerUnit)
        {
            ref var command = ref commandBuffer.Create<SpawnUnitCommand>();
            command.Position = position;
            command.Rotation = rotation;
            command.UnitType = unitType;
            command.IsPlayerUnit = isPlayerUnit;
        }
    }
}

